import Link from "next/link";
import { ArrowLeft, Sparkles, Star } from "lucide-react";
import { Card } from "@/components/ui/card";
import { getEngagementProvider } from "@/lib/engagement/provider";
import { buildMarketplaceLeaderboards } from "@/lib/marketplace/growth";
import { getMarketplaceProvider } from "@/lib/marketplace/provider";
import { getTrustProvider } from "@/lib/trust/provider";

export default async function DiscoveryTopPage() { const [marketplaceProvider, engagementProvider, trustProvider] = await Promise.all([getMarketplaceProvider(), getEngagementProvider(), getTrustProvider()]); const [runtime, engagementState, trustState] = await Promise.all([marketplaceProvider.readRuntime(), engagementProvider.readState(), trustProvider.readState()]); const leaderboards = buildMarketplaceLeaderboards(runtime, engagementState, trustState); return <main className="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-10 lg:py-8"><Card className="rounded-[36px] p-6 sm:p-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="surface-label text-[#d7ffab]">Top in market</p><h1 className="mt-4 text-balance text-4xl font-semibold sm:text-5xl" data-display="true">The most trusted and most booked chairs right now</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/64">This route makes ranking visible to clients without forcing them through dense reporting or admin-first screens.</p></div><div className="flex flex-wrap gap-3"><Link href="/discover" className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-black/25 px-5 py-3 text-[11px] font-semibold uppercase tracking-[0.22em] text-white transition hover:border-[#7CFF00]/24 hover:text-[#d7ffab]"><ArrowLeft className="h-4 w-4" />Back to discover</Link><Link href="/leaderboards" className="inline-flex items-center gap-2 rounded-full border border-[#cfff93]/40 bg-[linear-gradient(135deg,#7cff00_0%,#b7ff58_100%)] px-5 py-3 text-[11px] font-semibold uppercase tracking-[0.22em] text-black shadow-[0_14px_34px_rgba(124,255,0,0.24)] transition hover:translate-y-[-1px] hover:shadow-[0_18px_38px_rgba(124,255,0,0.28)]"><Sparkles className="h-4 w-4" />Full leaderboards</Link></div></div></Card><section className="mt-4 grid gap-4 lg:grid-cols-2">{[{ title: "Top rated", icon: Star, rows: leaderboards.topRated }, { title: "Most booked", icon: Sparkles, rows: leaderboards.mostBooked }].map((section) => { const Icon = section.icon; return <Card key={section.title} className="rounded-[32px] p-6"><div className="flex items-center justify-between gap-3"><p className="surface-label">{section.title}</p><Icon className="h-5 w-5 text-[#baff69]" /></div><div className="mt-4 space-y-3">{section.rows.map((entry, index) => <div key={`${section.title}-${entry.barberId}`} className="rounded-[22px] border border-white/8 bg-black/20 p-4 transition hover:border-[#7CFF00]/18 hover:bg-black/30"><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-medium">#{index + 1} {entry.barberName}</p><span className="status-pill text-[#d7ffab]">{entry.scoreLabel}</span></div><p className="mt-2 text-sm text-white/58">{entry.supportingText}</p></div>)}</div></Card>; })}</section></main>; }

